[Mysql]
# Host 和 Pwd 信息较敏感，放环境变量，详见 ./config.go 的 initConfig()
Database = "hdu_help"
User = "root"
Port = "3306"

[OSS]
# 阿里云 OSS region，华东1，杭州
EndPoint = "http://oss-cn-hangzhou.aliyuncs.com"
# 阿里云 bucket，为助手单开的一个 bucket
BucketName = "bird-hduhelp"